version: '3.3'
services:
# ===== MySQL SERVER CONFIG ======== #
# ================================== #
  mysql:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
# ===== RAILS SERVER CONFIG ======== #
# ================================== #
  rails:
    build:
      context: .
      # network: host
      dockerfile: Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid || true && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      # - DATABASE_NAME=task-manager
      - DATABASE_USER=root
      - DATABASE_HOST=mysql
      - DATABASE_PASSWORD=root
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    stdin_open: true
    tty: true
# ======== DATABASE VOLUMES ======== #
# ================================== #
volumes:
  mysql-volume:
